name: WoW Build Tools - TOC Check
description: Check for common issues in your World of Warcraft addon TOC files.
branding:
  icon: zap
  color: blue

inputs:
  args:
    description: Arguments to pass to `wow-build-tools toc check`.
    required: false
    default: ""

runs:
  using: docker
  image: ../Dockerfile
  args:
    - /toc/check
    - ${{ inputs.args }}
