name: WoW Build Tools
description: Build and release your World of Warcraft addons with ease.
branding:
  icon: zap
  color: blue

inputs:
  args:
    description: Arguments to pass to `wow-build-tools build`.
    required: false
    default: ""

outputs:
  package-name:
    description: The name of the package that was built.
  main-zip-path:
    description: The path to the main zip file that was built.
  nolib-zip-path:
    description: The path to the nolib zip file that was built, if applicable.
  project-version:
    description: The determined version of the project.

runs:
  using: composite
  steps:
    - name: Handle inputs
      id: handle-inputs
      shell: bash
      run: |
        set -euo pipefail

        # TODO: Add options to the action itself rather than just args
        if [ -z "${{ inputs.args }}" ]; then
          INPUT_ARGS=""
        else

        INPUT_ARGS="${{ inputs.args }}"

        echo "INPUT_ARGS=${INPUT_ARGS}" >> $GITHUB_OUTPUT
    - name: Run wow-build-tools
      shell: bash
      run: |
        set -euo pipefail

        ${GITHUB_ACTION_PATH}/dist/wow-build-tools build ${{ steps.handle-inputs.outputs.INPUT_ARGS }}
