name: WoW Build Tools
description: Build and release your World of Warcraft addons with ease.
branding:
  icon: zap
  color: blue

inputs:
  args:
    description: Arguments to pass to `wow-build-tools build`.
    required: false
    default: ""

outputs:
  package-name:
    description: The name of the package that was built.
  main-zip-path:
    description: The path to the main zip file that was built.
  nolib-zip-path:
    description: The path to the nolib zip file that was built, if applicable.
  project-version:
    description: The determined version of the project.

env:
  IMAGE: ghcr.io/mctalian/wow-build-tools:${GITHUB_SHA}

runs:
  using: docker
  image: ${IMAGE}
  args:
    - ${{ inputs.args }}
