name: WoW Build Tools - TOC Update
description: Update the interface version(s) in your World of Warcraft addon TOC files.
branding:
  icon: zap
  color: blue

inputs:
  args:
    description: Arguments to pass to `wow-build-tools toc check`.
    required: false
    default: ""

runs:
  using: docker
  image: ../../Dockerfile
  args:
    - /toc/update
    - ${{ inputs.args }}
