name: Build dist on main
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

permissions: {}

jobs:
  build-dist:
    name: Build Binary for Action
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build dist
        run: |
          mkdir -p dist
          go build -o dist/wow-build-tools

      - name: Smoke test built binary
        run: |
          ./dist/wow-build-tools --help

      - name: Commit and push dist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: build linux dist binary"
            git push
          fi

  release:
    name: Create
    needs: [build-dist]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          ref: beta # Explicitly fetch the latest from the branch

      - name: Pull latest changes
        run: |
          git pull origin beta

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
