name: PR Checks
on:
  pull_request:

permissions: {}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: wow-build-tools:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Smoke test Docker image
        run: |
          docker run --volume $(pwd):/github/workspace --rm wow-build-tools:pr-${{ github.event.pull_request.number }} /build --help

  trunk-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Go cache paths
        id: go-cache-paths
        run: |
          GOPATHBIN=$(go env GOPATH)/bin
          [ -d $(go env GOCACHE) ] && chmod -R 0755 $(go env GOCACHE)
          [ -d $(go env GOMODCACHE) ] && chmod -R 0755 $(go env GOMODCACHE)
          [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install Go dependencies
        run: go mod download

      - name: Declare Tools
        id: declare-tools
        run: |
          touch go.tools.txt
          echo "github.com/medyagh/gopogh/cmd/gopogh@1885ea840fbc9b32f018d792342adb919b7b9009" >> go.tools.txt
          echo "github.com/cancue/covreport@3fe392bcb4a978ff1f94dbf1367d992c4b3a67d6" >> go.tools.txt

      - name: Go Tool Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-tool }}
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.tools.txt') }}

      - name: Install tools
        run: |
          for tool in $(cat go.tools.txt); do
            go install "$tool"
          done

          which gopogh
          which covreport

      - name: Run tests
        run: |
          echo "Creating coverage directory"
          mkdir -p ./.coverage
          echo "Running tests with coverage"
          go test -v ./... -coverpkg=./... -coverprofile="./.coverage/cover.out" -json > .coverage/test-report.json || true
          echo "Generating test report"
          gopogh -in .coverage/test-report.json -out_summary .coverage/test-summary.json
          echo "Generating coverage reports: Cover"
          go tool cover -html=./.coverage/cover.out -o .coverage/cover.html
          echo "Generating coverage reports: Covreport"
          covreport -i .coverage/cover.out -o .coverage/report.html
          echo "Test Summary:"
          NumberPassed=$(cat ./.coverage/test-summary.json | jq '.NumberOfPass')
          NumFailed=$(cat ./.coverage/test-summary.json | jq '.NumberOfFail')
          TotalTests=$(cat ./.coverage/test-summary.json | jq '.NumberOfTests')
          TotalTime=$(cat ./.coverage/test-summary.json | jq '.TotalDuration')
          echo "Tests passed: $NumberPassed / $TotalTests in $TotalTime seconds."
          if [ "$NumFailed" -ne "0" ]; then
            exit 1
          fi

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./.coverage
          include-hidden-files: true

  all_pr_checks:
    name: Passing PR Checks
    runs-on: ubuntu-latest
    if: always()
    needs: [trunk-check, test, docker-build]
    steps:
      - name: Export needs results as JSON
        id: export-needs
        run: echo '${{ toJSON(needs) }}' > needs.json

      - name: Check if all jobs passed or were skipped
        run: |
          needs=$(cat needs.json)
          for job in $(echo "$needs" | jq -r 'keys[]'); do
            result=$(echo "$needs" | jq -r ".\"$job\".result")
            if [[ "$result" != "success" && "$result" != "skipped" ]]; then
              echo "Job $job failed."
              exit 1
            fi
          done
          echo "All jobs passed or were skipped."
        shell: bash
