name: Verify, Build, and Release
on:
  push:
    branches: [main, beta, alpha]
    paths:
      - "**/*"
      - "!dist/**"

permissions: {}

concurrency:
  group: push-main
  cancel-in-progress: false

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Go cache paths
        id: go-cache-paths
        run: |
          GOPATHBIN=$(go env GOPATH)/bin
          [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
          echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT

      - name: Install Go dependencies
        run: go mod download

      - name: Go Tool Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-tool }}
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.tools') }}

      - name: Install tools
        run: |
          for tool in $(cat go.tools); do
            go install "$tool"
          done

      - name: Run tests
        run: CC_THRESHOLD=10 ./scripts/test.sh

      - name: Upload test and coverage reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: ./.coverage
          include-hidden-files: true

  trigger-dist:
    name: Release
    permissions:
      contents: write
    needs: [trunk-check, test]
    uses: ./.github/workflows/build-dist-main.yml
    secrets: inherit
