name: Semantic Release
on:
  push:
    branches: [main, beta, alpha]

permissions: {}

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Go cache paths
        id: go-cache-paths
        run: |
          GOPATHBIN=$(go env GOPATH)/bin
          [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
          echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT

      - name: Install Go dependencies
        run: go mod download

      - name: Go Tool Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-tool }}
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.tools') }}

      - name: Install tools
        run: |
          for tool in $(cat go.tools); do
            go install "$tool"
          done

      - name: Run tests
        run: |
          echo "Creating temp directories..."
          mkdir -p ./.coverage
          # mkdir -p ./.test-results
          echo "Running tests..."
          go test -v ./... -cover -coverpkg=./... -coverprofile="./.coverage/.cover.out"
          echo "Generating coverage report..."
          go tool cover -html="./.coverage/.cover.out" -o "./.coverage/report.html"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./.coverage
          include-hidden-files: true

  check-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Smoke test built binary
        run: |
          dist/wow-build-tools build --help

  release:
    needs: [trunk-check, test, check-dist]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
