name: Release
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

permissions: {}

jobs:
  release:
    name: Build Binary and Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install Go dependencies
        run: go mod download

      - name: Build dist
        run: |
          mkdir -p dist
          go build -o dist/wow-build-tools

      - name: Smoke test built binary
        run: |
          ./dist/wow-build-tools --help

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Node dependencies
        run: npm install

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
