name: Verify, Build, and Release
on:
  push:
    branches: [main]
    paths:
      - "**"
      - "!dist/**"

permissions: {}

concurrency:
  group: push-main
  cancel-in-progress: false

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Go cache paths
        id: go-cache-paths
        run: |
          GOPATHBIN=$(go env GOPATH)/bin
          [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
          echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT

      - name: Install Go dependencies
        run: go mod download

      - name: Go Tool Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.go-cache-paths.outputs.go-tool }}
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.tools') }}

      - name: Install tools
        run: |
          for tool in $(cat go.tools); do
            go install "$tool"
          done

      - name: Run tests
        run: CC_THRESHOLD=10 ./scripts/test.sh

      - name: Upload test and coverage reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: ./.coverage
          include-hidden-files: true

  release:
    name: Release
    permissions:
      contents: write
    needs: [trunk-check, test]
    uses: ./.github/workflows/wbt-release.yml
    secrets: inherit
