name: Release
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

permissions: {}

jobs:
  release:
    name: Build Binary and Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install Go dependencies
        run: go mod download

      - name: Build dist
        run: |
          mkdir -p dist
          go build -o dist/wow-build-tools

      - name: Smoke test built binary
        run: |
          ./dist/wow-build-tools --help

      - name: Setup Node.js
        uses: volta-cli/action@615a78f6c83e116339c53b94f3f82b4d6c0b7d18 # v5.0.0

      - name: Install Node dependencies
        run: npm install

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
